services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "ny_taxi"
    networks:
      - my_special_network
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    networks:
      - my_special_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:

networks:
  my_special_network:      
    name: taxi-network
